services:
  # Node App
  - type: web
    plan: free # optional (defaults to starter)
    name: node-red
    env: node
    repo: https://github.com/lebalz/node-red-render.git
    buildCommand: npm install;
    startCommand: node --max-old-space-size=384 node_modules/node-red/red.js --settings ./settings.js;
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elephant
          property: connectionString
      - key: NODE_RED_USERNAME
        value: admin
      - key: NODE_RED_PASSWORD
        sync: false
databases:
  - name: elephant
    plan: free # optional (defaults to starter)
    databaseName: nodered # optional (Render may add a suffix)
    user: nodered # optional